# Compiler
CXX = g++
CXXFLAGS = -std=c++17 -Wall -O2

# Targets
TARGETS = kosarajuByList

all: $(TARGETS)

Q3: kosarajuByList.cpp
	$(CXX) $(CXXFLAGS) -o kosarajuByList kosarajuByList.cpp

clean:
	rm -f $(TARGETS)